# Generated by Django 4.2.3 on 2023-08-05 15:35

import django.core.validators
from django.db import migrations, models
import web_project.accounts.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), web_project.accounts.models.validate_only_alphabetical]),
        ),
    ]
